### ISSUE TITLE
/f info <faction> bug

### ISSUE THREAD

**Issue by CupidonSauce173** [poggit-orphanage/FactionsPro_1.4#13] opened 2018-05-25 21:21 UTC
when you do /f info <faction> it works but it show that there is no Leader, no Members and no Description. 

1.Install FactionPro_1.4
2.Do /f create test
3.Do /f info test

**Comment by Awzaw** [comment] 2018-12-15 21:34
Can't reproduce, closing.

**Closed as completed by Awzaw** 2018-12-15 21:34 UTC
