### ISSUE TITLE
Error: "Call to a member function getName() on null" (EXCEPTION) in "FactionsPro_1.4_dev-27.phar/src/FactionsPro/FactionListener" at line 103

### ISSUE THREAD

**Issue by teracube** [poggit-orphanage/FactionsPro_1.4#9] opened 2017-11-25 09:56 UTC
hello
i found this plugin issue
sorry i don't know how to reproduce

FactionsPro_1.4_dev-27 latest build
PocketMine-MP_1.7dev-451
Linux
PHP 7.2 RC4

```2017-11-25 [10:26:51] [Server thread/CRITICAL]: Error: "Call to a member function getName() on null" (EXCEPTION) in "FactionsPro_1.4_dev-27.phar/src/FactionsPro/FactionListener" at line 103
2017-11-25 [10:26:51] [Server thread/DEBUG]: #0 src/pocketmine/plugin/MethodEventExecutor(38): FactionsPro\FactionListener->factionBlockBreakProtect(pocketmine\event\block\BlockBreakEvent object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #1 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(FactionsPro\FactionListener object, pocketmine\event\block\BlockBreakEvent object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginManager(721): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\block\BlockBreakEvent object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #3 src/pocketmine/level/Level(1649): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\block\BlockBreakEvent object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #4 src/pocketmine/Player(2317): pocketmine\level\Level->useBreakOn(pocketmine\math\Vector3 object, pocketmine\item\ItemBlock object, pocketmine\Player object, boolean 1)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(132): pocketmine\Player->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(149): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #10 src/pocketmine/Player(2999): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #11 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #12 vendor/pmmp/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 82.227.93.250:57058, raklib\protocol\EncapsulatedPacket object, integer 0)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #13 src/pocketmine/network/mcpe/RakLibInterface(84): raklib\server\ServerHandler->handlePacket()
2017-11-25 [10:26:51] [Server thread/DEBUG]: #14 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
2017-11-25 [10:26:51] [Server thread/DEBUG]: #15 src/pocketmine/Server(2516): pocketmine\network\Network->processInterfaces()
2017-11-25 [10:26:51] [Server thread/DEBUG]: #16 src/pocketmine/Server(2272): pocketmine\Server->tick()
2017-11-25 [10:26:51] [Server thread/DEBUG]: #17 src/pocketmine/Server(2147): pocketmine\Server->tickProcessor()
2017-11-25 [10:26:51] [Server thread/DEBUG]: #18 src/pocketmine/Server(1735): pocketmine\Server->start()
2017-11-25 [10:26:51] [Server thread/DEBUG]: #19 src/pocketmine/PocketMine(552): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/, string /home/gsp_1485/g3.hmserv.eu-19144/, string /home/gsp_1485/g3.hmserv.eu-19144/plugins/)
2017-11-25 [10:26:51] [Server thread/DEBUG]: #20 /home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar(1): require(string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/src/pocketmine/PocketMine.php)```

**Comment by Awzaw** [comment] 2018-12-15 21:32
Can't reproduce, closing.

**Closed as completed by Awzaw** 2018-12-15 21:32 UTC
